services:
  server:
    image: ${SERVER_IMAGE}
    build:
      context: ..
      dockerfile: server-go/Dockerfile
    container_name: ${SERVER_CONTAINER_NAME}
    ports:
      - "${HOST_PORT}:8080"
    volumes:
      - ./apk:/opt/vocdoni/downloads:ro
    environment:
      VOCDONI_PUBLIC_BASE_URL: ${VOCDONI_PUBLIC_BASE_URL}
      VOCDONI_SERVER_LISTEN: ${VOCDONI_SERVER_LISTEN}
      VOCDONI_LOG_LEVEL: ${VOCDONI_LOG_LEVEL}
      VOCDONI_APK_PATH: ${VOCDONI_APK_PATH}
      VOCDONI_PROVER_LOW_MEMORY_MODE: ${VOCDONI_PROVER_LOW_MEMORY_MODE}
      VOCDONI_PROVER_MAX_STORAGE_USAGE: ${VOCDONI_PROVER_MAX_STORAGE_USAGE}
      VOCDONI_PROVER_TIMEOUT: ${VOCDONI_PROVER_TIMEOUT}
      VOCDONI_PROVER_MAX_CONCURRENCY: ${VOCDONI_PROVER_MAX_CONCURRENCY}
      VOCDONI_PROVER_BINARY_PATH: ${VOCDONI_PROVER_BINARY_PATH}
      BB_BINARY_PATH: ${BB_BINARY_PATH}
      VOCDONI_WORKSPACE_ROOT: ${VOCDONI_WORKSPACE_ROOT}
      VOCDONI_ARTIFACTS_DIR: ${VOCDONI_ARTIFACTS_DIR}
    restart: unless-stopped
